version: '3.9'

services:
  pingtrace:
    build: .
    container_name: pingtrace-api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /home/myu/Documents/Git/Ping-API-Project/api:/app/api
    


networks:
  Main:
    name: Main
    driver: bridge